[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_stablecoin_standard = "8kY3yQGTdrvPRG3SQfjwyf3SuuUW9Wt1W8zFwURTpa59"
sss_transfer_hook = "DbEuNBSDNQp1ijdX7qhnLX7qVfqVMDcjBWiGeUqhaY5w"

[programs.devnet]
solana_stablecoin_standard = "8kY3yQGTdrvPRG3SQfjwyf3SuuUW9Wt1W8zFwURTpa59"
sss_transfer_hook = "DbEuNBSDNQp1ijdX7qhnLX7qVfqVMDcjBWiGeUqhaY5w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/solana-stablecoin-standard", "programs/sss-transfer-hook"]
