import { EventEmitter } from 'events';
import { Connection, PublicKey, Logs } from '@solana/web3.js';
import * as borsh from '@coral-xyz/anchor/dist/cjs/utils/borsh';

// ---- Event type definitions ------------------------------------------------

export interface TokensMintedEvent {
  mint: string;
  recipient: string;
  amount: bigint;
  totalSupply: bigint;
  slot: number;
  signature: string;
}

export interface TokensBurnedEvent {
  mint: string;
  from: string;
  amount: bigint;
  totalSupply: bigint;
  slot: number;
  signature: string;
}

export interface TokensTransferredEvent {
  mint: string;
  from: string;
  to: string;
  amount: bigint;
  slot: number;
  signature: string;
}

export interface AccountFreezeUpdatedEvent {
  mint: string;
  account: string;
  frozen: boolean;
  reason: string;
  authority: string;
  slot: number;
  signature: string;
}

export interface WhitelistUpdatedEvent {
  mint: string;
  wallet: string;
  approved: boolean;
  expiresAt: number | null;
  kycRef: string;
  authority: string;
  slot: number;
  signature: string;
}

export interface FundsSeizedEvent {
  mint: string;
  from: string;
  to: string;
  amount: bigint;
  reason: string;
  authority: string;
  slot: number;
  signature: string;
}

export type SSSEvent =
  | { type: 'TokensMinted'; data: TokensMintedEvent }
  | { type: 'TokensBurned'; data: TokensBurnedEvent }
  | { type: 'TokensTransferred'; data: TokensTransferredEvent }
  | { type: 'AccountFreezeUpdated'; data: AccountFreezeUpdatedEvent }
  | { type: 'WhitelistUpdated'; data: WhitelistUpdatedEvent }
  | { type: 'FundsSeized'; data: FundsSeizedEvent };

// Anchor event discriminator: first 8 bytes of sha256("event:<EventName>")
// We identify log lines that contain "Program data: <base64>" for our program.
const PROGRAM_DATA_PREFIX = 'Program data: ';

// Mapping from Anchor event discriminator hex prefix to event type name.
// These must match the discriminators generated by Anchor for the SSS program.
// In practice you would compute these from the IDL; here we use the standard
// sha256("event:EventName") truncated to 8 bytes approach.
import * as crypto from 'crypto';

function eventDiscriminator(name: string): Buffer {
  return crypto.createHash('sha256').update(`event:${name}`).digest().subarray(0, 8);
}

const EVENT_DISCRIMINATORS = new Map<string, string>([
  [eventDiscriminator('TokensMinted').toString('hex'), 'TokensMinted'],
  [eventDiscriminator('TokensBurned').toString('hex'), 'TokensBurned'],
  [eventDiscriminator('TokensTransferred').toString('hex'), 'TokensTransferred'],
  [eventDiscriminator('AccountFreezeUpdated').toString('hex'), 'AccountFreezeUpdated'],
  [eventDiscriminator('WhitelistUpdated').toString('hex'), 'WhitelistUpdated'],
  [eventDiscriminator('FundsSeized').toString('hex'), 'FundsSeized'],
]);

// ---- Borsh deserialization schemas -----------------------------------------
// These must align exactly with the Anchor account/event field ordering.

function decodePubkey(buf: Buffer, offset: number): [string, number] {
  const bytes = buf.subarray(offset, offset + 32);
  return [new PublicKey(bytes).toBase58(), offset + 32];
}

function decodeU64(buf: Buffer, offset: number): [bigint, number] {
  const val = buf.readBigUInt64LE(offset);
  return [val, offset + 8];
}

function decodeI64(buf: Buffer, offset: number): [bigint, number] {
  const val = buf.readBigInt64LE(offset);
  return [val, offset + 8];
}

function decodeBool(buf: Buffer, offset: number): [boolean, number] {
  return [buf[offset] !== 0, offset + 1];
}

function decodeString(buf: Buffer, offset: number): [string, number] {
  const len = buf.readUInt32LE(offset);
  offset += 4;
  const str = buf.subarray(offset, offset + len).toString('utf8');
  return [str, offset + len];
}

function decodeOptionI64(buf: Buffer, offset: number): [number | null, number] {
  const some = buf[offset] !== 0;
  offset += 1;
  if (!some) return [null, offset];
  const val = buf.readBigInt64LE(offset);
  return [Number(val), offset + 8];
}

function parseEventData(eventType: string, buf: Buffer, signature: string, slot: number): SSSEvent | null {
  // Skip the 8-byte discriminator
  let off = 8;
  try {
    switch (eventType) {
      case 'TokensMinted': {
        const [mint, o1] = decodePubkey(buf, off);
        const [recipient, o2] = decodePubkey(buf, o1);
        const [amount, o3] = decodeU64(buf, o2);
        const [totalSupply] = decodeU64(buf, o3);
        return { type: 'TokensMinted', data: { mint, recipient, amount, totalSupply, slot, signature } };
      }
      case 'TokensBurned': {
        const [mint, o1] = decodePubkey(buf, off);
        const [from, o2] = decodePubkey(buf, o1);
        const [amount, o3] = decodeU64(buf, o2);
        const [totalSupply] = decodeU64(buf, o3);
        return { type: 'TokensBurned', data: { mint, from, amount, totalSupply, slot, signature } };
      }
      case 'TokensTransferred': {
        const [mint, o1] = decodePubkey(buf, off);
        const [from, o2] = decodePubkey(buf, o1);
        const [to, o3] = decodePubkey(buf, o2);
        const [amount] = decodeU64(buf, o3);
        return { type: 'TokensTransferred', data: { mint, from, to, amount, slot, signature } };
      }
      case 'AccountFreezeUpdated': {
        const [mint, o1] = decodePubkey(buf, off);
        const [account, o2] = decodePubkey(buf, o1);
        const [frozen, o3] = decodeBool(buf, o2);
        const [reason, o4] = decodeString(buf, o3);
        const [authority] = decodePubkey(buf, o4);
        return { type: 'AccountFreezeUpdated', data: { mint, account, frozen, reason, authority, slot, signature } };
      }
      case 'WhitelistUpdated': {
        const [mint, o1] = decodePubkey(buf, off);
        const [wallet, o2] = decodePubkey(buf, o1);
        const [approved, o3] = decodeBool(buf, o2);
        const [expiresAt, o4] = decodeOptionI64(buf, o3);
        const [kycRef, o5] = decodeString(buf, o4);
        const [authority] = decodePubkey(buf, o5);
        return { type: 'WhitelistUpdated', data: { mint, wallet, approved, expiresAt, kycRef, authority, slot, signature } };
      }
      case 'FundsSeized': {
        const [mint, o1] = decodePubkey(buf, off);
        const [from, o2] = decodePubkey(buf, o1);
        const [to, o3] = decodePubkey(buf, o2);
        const [amount, o4] = decodeU64(buf, o3);
        const [reason, o5] = decodeString(buf, o4);
        const [authority] = decodePubkey(buf, o5);
        return { type: 'FundsSeized', data: { mint, from, to, amount, reason, authority, slot, signature } };
      }
      default:
        return null;
    }
  } catch (err) {
    console.error(`Failed to decode ${eventType} event:`, err);
    return null;
  }
}

function extractMintFromEvent(event: SSSEvent): string {
  return event.data.mint;
}

// ---- Listener class --------------------------------------------------------

const INITIAL_BACKOFF_MS = 1_000;
const MAX_BACKOFF_MS = 60_000;
const BACKOFF_MULTIPLIER = 2;

export class SSSEventListener extends EventEmitter {
  private connection: Connection;
  private programId: PublicKey;
  private subscriptionId: number | null = null;
  private stopped = false;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private backoffMs = INITIAL_BACKOFF_MS;

  constructor(connection: Connection, programId: PublicKey) {
    super();
    this.connection = connection;
    this.programId = programId;
  }

  async start(): Promise<void> {
    this.stopped = false;
    this.backoffMs = INITIAL_BACKOFF_MS;
    await this.subscribe();
  }

  stop(): void {
    this.stopped = true;
    if (this.reconnectTimer !== null) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    if (this.subscriptionId !== null) {
      this.connection.removeOnLogsListener(this.subscriptionId).catch((err) => {
        console.error('Error removing logs listener:', err);
      });
      this.subscriptionId = null;
    }
  }

  private async subscribe(): Promise<void> {
    try {
      this.subscriptionId = this.connection.onLogs(
        this.programId,
        (logs: Logs) => this.handleLogs(logs),
        'confirmed',
      );
      console.log(`Subscribed to SSS program logs (subscription ${this.subscriptionId})`);
      // Reset backoff on successful subscribe
      this.backoffMs = INITIAL_BACKOFF_MS;
    } catch (err) {
      console.error('Failed to subscribe to program logs:', err);
      this.scheduleReconnect();
    }
  }

  private handleLogs(logs: Logs): void {
    if (logs.err) {
      // Skip failed transactions — they still emit logs but events are meaningless
      return;
    }

    for (const log of logs.logs) {
      if (!log.startsWith(PROGRAM_DATA_PREFIX)) continue;

      const b64 = log.slice(PROGRAM_DATA_PREFIX.length).trim();
      let buf: Buffer;
      try {
        buf = Buffer.from(b64, 'base64');
      } catch {
        continue;
      }

      if (buf.length < 8) continue;

      const discriminatorHex = buf.subarray(0, 8).toString('hex');
      const eventType = EVENT_DISCRIMINATORS.get(discriminatorHex);
      if (!eventType) continue;

      // Slot is not in the log callback — we fetch it from the context
      // The Logs type has `signature` but not `slot`; we use 0 as a placeholder
      // and let downstream consumers fetch the slot from the signature if needed.
      const event = parseEventData(eventType, buf, logs.signature, 0);
      if (!event) continue;

      const mint = extractMintFromEvent(event);
      this.emit('event', event.type, event.data, mint);
    }
  }

  private scheduleReconnect(): void {
    if (this.stopped) return;
    console.log(`Reconnecting in ${this.backoffMs}ms...`);
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      if (!this.stopped) {
        void this.subscribe();
      }
    }, this.backoffMs);
    this.backoffMs = Math.min(this.backoffMs * BACKOFF_MULTIPLIER, MAX_BACKOFF_MS);
  }
}

// Suppress unused import warning — borsh is a peer dep used at runtime by Anchor
void (borsh as unknown);
